### ISSUE TITLE
Is nginx forwarding all the users requests to the path-manager or this is just for claiming path internally?

### ISSUE THREAD

**Issue by zv3** [guardian/path-manager#14]
I haven't had the time yet to try it myself but I like the rationale behind the project. I have one question though, is this just intended for the micro services to reserve a certain path, so that the rest of the micro services don't claim the same path? or the path-manager is also the service that would handle all user requests coming in and redirecting them to a registered system with the id that was given to said system for claiming the path?

Thanks!

**Comment by sihil** [comment]
Hi @zv3 - this is to allow micro services to reserve a path, it doesn't do any routing. Our multiple backend services all publish into our Content API which is the source of truth that our website uses to render content. This architecture helps us to scale more reliably without having to scale multiple backend systems.
